Feature/np 19
CS4273-TeamViper/cs4273_fa2023_notams pull request #2
Opened 2023-09-20 21:10 UTC by Dhadds

The app is now functioning. I will create a README that will help but we will inevitably have to overcome some setup issues when you guys move this onto your machines.

2023-09-20 22:49 UTC, tanminivan requested changes
It looks like we're still getting a lot of cruft added to the repo (pyc files, etc). It looks like we missed populating our `.gitignore` with data from gitignore.io to ignore common types. I went ahead and created a task for that (NP-35) and started PR to get that merged.

This will be a little bit complex to work in those changes to this branch so that we remove those unnecessary files, but we can work through it together if you'd like. The general idea is once my PR is merged, you'll want to rebase off of `main`, however the commit must be edited so that the ignored files will actually be ignored.

2023-09-20 23:10 UTC, tanminivan commented
I'd also like to see these two commits squashed into one. Let me know if you want to do a screenshare and I can go over squashing/rebasing, this would be a good example.

2023-09-21 05:56 UTC, chase-c55 commented on frontend/Dockerfile
> +# RUN npm install
What are these extra comments for? Are we missing code or are they unnecessary?

2023-09-21 05:58 UTC, chase-c55 requested changes
Are you creating the README in the repo to set this up or will that be in Notion?

2023-09-21 14:55 UTC, tanminivan commented
> Are you creating the README in the repo to set this up or will that be in Notion?

I think you could go either way on this, but a README in the repo feels like the better option to me, just so you can more easily track changes. Less likely to get out of date.

2023-10-02 20:05 UTC, Dhadds commented on frontend/Dockerfile
> +# RUN npm install
I do not know.

2023-10-02 22:11 UTC, tanminivan approved these changes

2023-10-02 22:26 UTC, Dhadds commented on frontend/Dockerfile
> +# RUN npm install
I removed these lines.

2023-10-02 22:35 UTC, Koy-Wilson approved these changes

2023-10-03 03:30 UTC, chase-c55 approved these changes

2023-10-03 11:21 UTC, merged