[NP-12] Add code to put NOTAMs into object for sorting
CS4273-TeamViper/cs4273_fa2023_notams pull request #4
Opened 2023-09-27 18:58 UTC by Koy-Wilson

2023-09-27 19:40 UTC, tanminivan requested changes

2023-09-27 19:40 UTC, tanminivan commented on all_notams.py
> +# Get the total number of pages incase we must deal with pagination
in case

2023-09-27 19:40 UTC, tanminivan commented on all_notams.py
> +total_pages = json_string["totalPages"]
calling this `json_string` makes it sound like this will be a string when you are fetching an int. Maybe just call it `json`? or `raw_json`?

2023-09-27 19:40 UTC, tanminivan commented on all_notams.py
> +    url = f"https://external-api.faa.gov/notamapi/v1/notams?domesticLocation={endLocation}&pageNum={index}"
Might be a good idea to distinguish this from `url` on line 15. `paged_url` or `indexed_url` or something similar.

2023-09-27 19:40 UTC, tanminivan commented on all_notams.py
> +for index in range(1, total_pages + 1):
does `pageNum` start at 1 or 0?

2023-09-27 19:40 UTC, tanminivan commented on all_notams.py
> +for index in range(1, total_pages + 1):
if `total_pages` is 1, are we going to fetch page `1` and `2`?

2023-09-27 19:40 UTC, tanminivan commented on all_notams.py
> +            notams[entry["properties"]["coreNOTAMData"]["notam"]["number"]] = entry
I'd break this up into two lines to make this a little bit more readable:

```python
notam_number = entry["properties"]["coreNOTAMData"]["notam"]["number"]
notams[notam_number] = entry
```

2023-09-27 19:40 UTC, tanminivan commented on all_notams.py
> +        if(entry["properties"]["coreNOTAMData"]["notamTranslation"][0]["type"] != "ICAO"):
The `[0]` gives me pause here. Are we always certain we will get the first entry here?

2023-09-27 19:40 UTC, tanminivan commented on all_notams.py
> +        if(entry["properties"]["coreNOTAMData"]["notamTranslation"][0]["type"] != "ICAO"):
Is it better to filter out ICAO or only include domestic?

2023-09-27 19:40 UTC, tanminivan commented on all_notams.py
> +    notamsArray.append(current)
I think you could just do
```python
notams_array = list( notams.values() )
```

2023-09-27 21:58 UTC, Koy-Wilson commented on all_notams.py
> +for index in range(1, total_pages + 1):
It starts at 1

2023-09-27 22:02 UTC, Koy-Wilson commented on all_notams.py
> +for index in range(1, total_pages + 1):
No, the range() method is exclusive for the second parameter so it will be range(1, 2). The only value in that range would be 1.

2023-09-27 22:11 UTC, chase-c55 approved these changes

2023-09-27 22:22 UTC, Koy-Wilson commented on all_notams.py
> +        if(entry["properties"]["coreNOTAMData"]["notamTranslation"][0]["type"] != "ICAO"):
> The `[0]` gives me pause here. Are we always certain we will get the first entry here?

From what I have seen: yes. That key will be an array. The max size of the array will be 2 if it contains both ICAO and local. If both formats are in the array the local format has always appeared in the first element (from what I have seen). Therefore, if it contains a local format we insert into the array regardless if it also has an ICAO format or not. Otherwise if the array is size 1 then we will just need to see if it is ICAO or LOCAL_FORMAT.

> Is it better to filter out ICAO or only include domestic?

I assumed it would be better to filter it out if it does not include a local format. If it includes both local format and ICAO I stored it since we can sort it with the local format.

2023-09-28 00:59 UTC, tanminivan commented on all_notams.py
> +for index in range(1, total_pages + 1):
Ah, yeah, that's right

2023-09-29 02:14 UTC, tanminivan approved these changes

2023-09-29 02:15 UTC, merged