[NP-12] Retrieve NOTAMs from beginning and ending airport
CS4273-TeamViper/cs4273_fa2023_notams pull request #6
Opened 2023-10-02 20:41 UTC by Koy-Wilson

2023-10-02 20:56 UTC, LukeKirk0056 approved these changes

2023-10-02 21:04 UTC, chase-c55 commented on begin_end_notams.py
> +    notamsArray = list( notams.values() )
nit: spacing

2023-10-02 21:07 UTC, chase-c55 commented on haversine.py
> +    meters_to_mile = 1609
Are these constants? ALL_CAP_WITH_UNDERSCORES for constants

2023-10-02 21:10 UTC, chase-c55 requested changes

2023-10-02 21:10 UTC, chase-c55 commented on haversine.py
> +    a = math.sin(delta_phi / 2.0) ** 2 + math.cos(phi_1) * math.cos(phi_2) * math.sin(delta_lambda / 2.0) ** 2
Can you comment on what this is? Looks like pythagorean theorem right?

2023-10-02 21:10 UTC, chase-c55 commented on haversine.py
> +    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
Comment on this as well for clarity

2023-10-02 21:10 UTC, chase-c55 commented on haversine.py
> +haversine([35.23350665, 97.3627422], [30.28243, 87.11118])
What is this as well?

2023-10-02 22:48 UTC, Dhadds commented on haversine.py
> +    meters_to_mile = 1609
```suggestion
    METERS_TO_MILE = 1609
```
Would this be better?

2023-10-03 03:25 UTC, chase-c55 commented on haversine.py
> +    meters_to_mile = 1609
Yeah, there was another right below it as well I believe. @Dhadds

2023-10-03 15:47 UTC, tanminivan requested changes

2023-10-03 15:47 UTC, tanminivan commented on begin_end_notams.py
> +def getNotams(location, dict):
PEP8 conventions would be `get_notams`

2023-10-03 15:47 UTC, tanminivan commented on begin_end_notams.py
> +    url = f'https://external-api.faa.gov/notamapi/v1/notams?pageSize=1000&domesticLocation={location}'
This is a minor thing. 

Since you're handling multiple pages below, I'd probably just allow the API to default to whatever its default page size is. If you are thinking that you are trying to conserve API requests by getting more notams per request—you're not wrong but it might be considered a premature optimization. You know you have some levers here you can pull in the future if you are running up against your API limit. (As an aside, do we know for certain that fetching multiple pages counts against our API limit? I could see an argument that it should not, but I don't know how the FAA really counts it. The API page displays some usage data for your API key, you could probably do some testing and find out).

Another reason  you may want to leave out specifying a `pageSize` is a possible—though admittedly unlikely—scenario where the FAA restricts the number of notams returned to something like 500, and anything that specifies an amount above this is given an HTTP 400 Bad Request error. It's an easy fix, for sure, but how embarrassing to have that happen and displayed to your clients. This is a defensive programming technique, trying to "harden" your code against possible future changes, especially when you're dealing with an API that isn't under your control. "Trust but verify."

2023-10-03 15:47 UTC, tanminivan commented on begin_end_notams.py
> +        paged_url = f"https://external-api.faa.gov/notamapi/v1/notams?domesticLocation={location}&pageNum={index}"
I believe there is a bug here. Your first request specifies a `pageSize` of 1000. But your paged request here does not specify a `pageSize`, so I believe it will default to the default `pageSize`, which is 50.

So first request gets Notams 1 through 1000 and says there is a second page, but when you request here, you are getting notams 51 through 100, which you already fetched in the first request.

2023-10-03 15:47 UTC, tanminivan commented on begin_end_notams.py
> +        paged_url = f"https://external-api.faa.gov/notamapi/v1/notams?domesticLocation={location}&pageNum={index}"
Duplicate hardcoded URLs here is a code smell. What if the API URL changes in the future? You might open this file, change the first URL on line 9 and miss this URL here on line 18. Is there a way to refactor this so that the URL is a constant at the top of the file? This way if the API URL changes you only have one place to change it?

2023-10-03 15:47 UTC, tanminivan commented on begin_end_notams.py
> +def getNotams(location, dict):
`dict` is a pretty vague name. Could this be more specific?

2023-10-03 15:47 UTC, tanminivan commented on begin_end_notams.py
> +        items = json_string["items"]
You really only use `items` below on line 23, what about `for entry in json_string["items"]` ?

2023-10-03 15:47 UTC, tanminivan commented on begin_end_notams.py
> +
What about some debug logging here that might help you in the future? "Fetched N NOTAMs for OKC"

2023-10-03 15:47 UTC, tanminivan commented on begin_end_notams.py
> +        json_string = requests.get(paged_url, headers=headers).json()
What about error handling? What if the page is unavailable or you get a non-HTTP 200 response code?

2023-10-03 15:47 UTC, tanminivan commented on begin_end_notams.py
> +    file = open("sample_array.txt", "w")
I know we're working with some snippets here but maybe we could be more specific with this file name, like `notams.json` or maybe add the locations to the filename, so that you can build up several different files while you are testing: `notams_{startLocation}_{endLocation}.json`

2023-10-03 15:47 UTC, tanminivan commented on haversine.py
> +    radians = 6371000
Just `radians`?

2023-10-03 15:47 UTC, tanminivan commented on haversine.py
> +    print(f"The distance is: {miles}")
Might aid in testing to add the original lat/longs here to this message: "The distance between 97.1234,-105.814 and 98.359,-135.039 is 103.9345 miles"

2023-10-03 15:47 UTC, tanminivan commented on haversine.py
> +def haversine(coord1, coord2):
Could you add some unit tests here as well? Pick some known points with known distances and verify you are within 1% of that or something similar.

2023-10-03 15:47 UTC, tanminivan commented on begin_end_notams.py
> +def getNotams(location, dict):
Why pass a dict here to be modified instead of returning a new dict of those notams?

2023-10-03 15:47 UTC, tanminivan commented on begin_end_notams.py
We are building up some code snippets here of arbitrary files. Is there a place for this code within the `backend/` directory?

I am okay with leaving this file as-is provided there's another ticket to move this into our main code at a later time.

2023-10-03 15:47 UTC, tanminivan commented on haversine.py
> +haversine([35.23350665, 97.3627422], [30.28243, 87.11118])
Invoking the function with two points to display the distance.

2023-10-03 19:05 UTC, Koy-Wilson commented on haversine.py
> +    a = math.sin(delta_phi / 2.0) ** 2 + math.cos(phi_1) * math.cos(phi_2) * math.sin(delta_lambda / 2.0) ** 2
It is the haversine formula. I will comment the URL for the wikipedia page. It is simply matching the equation from there.

2023-10-03 19:11 UTC, Koy-Wilson commented on begin_end_notams.py
> +def getNotams(location, dict):
I call getNotams on both the starting and ending location wanted to created a dictionary in the main method and pass it in the function call to have all notams in a single dictionary instead of creating two dictionaries (since I have to call the function on both the start and end location) and merging those.

2023-10-03 19:13 UTC, Koy-Wilson commented on haversine.py
> +def haversine(coord1, coord2):
If we want unit tests we will have to break it up into a new task. I would prefer that somebody else picks that up unless we want to push back the timeline for me getting the enroute notams.

2023-10-03 19:17 UTC, Koy-Wilson commented on begin_end_notams.py
> +        json_string = requests.get(paged_url, headers=headers).json()
Not sure what to do unless we want to continuously call the method upon getting an error since without the API we don't have a product.

2023-10-03 20:18 UTC, tanminivan commented on begin_end_notams.py
> +        json_string = requests.get(paged_url, headers=headers).json()
It might be a good idea to display an error state to the user, right? "Could not contact FAA API, error details: xxxx"

2023-10-03 20:56 UTC, tanminivan commented on begin_end_notams.py
> +def getNotams(location, dict):
You're not wrong. If it were me, I'd do it more like this:

```python
def get_notams( location )
   ...

departure_notams = get_notams( 'OKC' )
destination_notams = get_notams( 'DFW' )
combined_notams = departure_notams | destination_notams
```

My reasoning behind this is that you don't write code for the _computer_, you write code for the _reader_ (which will likely be yourself in the future!). The code becomes more self-documenting. We clearly define the input (`location`) of the function and its output (dict of notams). The function becomes more more singularly focused—"give me the notams for this location"—instead of "give me the notams for this location _and_ put it in this dict for me." It's easier to see the flow of data and we can use these new variables to better describe what we expect. If we found some DFW notams in `departure_notams` we would know something is amiss. The code also becomes more parallelizable if you decided to go that way in the future.

You don't have to remember such details about "Wait, why do I need to pass a `dict` to this function to get notams? Does this function do something to this `dict` that I don't want it to, like clear it before fetching notams? How does it handle de-duplication? Do I need to put something in the dict beforehand? Do I need to call these in a specific order?" Some of these questions are a bit contrived for this example, but as code becomes more complex, they can come into play.

Like I said, you're not wrong. I'm just trying to provide some additional points of view and things to consider when developing software.

2023-10-03 21:41 UTC, tanminivan requested changes

2023-10-03 21:41 UTC, tanminivan commented on begin_end_notams.py
> +        print(f"Could not contact the FAA API. Code: {requests.get(url, headers=headers)}")
So, you're actually making a _second_ request here on line 18 instead of displaying what happened with the original request made on line 16.

It looks like the `requests` module gives back a response object:
```python
response = requests.get( url, headers=headers)
```
(note the lack of `.json()` at the end here)

And then you can read the status code of that response object with `response.status_code`. (see [docs here](https://pypi.org/project/requests/)).

It looks like getting back a non-200 HTTP error code is a case where an Exception is NOT raised. In this sample code I'm using `https://httpstat.us/500` to get an HTTP 500 error:

```python
import requests

try:
    response = requests.get( "https://httpstat.us/500" ) # this will give back HTTP 500
    print( f"Got response code {response.status_code}" )
except Exception as err:
    print("Got an exception")
    raise err
```
In this case, no exception is ever raised. The print statement within the `try` block is executed.

So I think you need to do two things here:

1. Add a check to make sure you get back an HTTP 200 status code. If you don't, you should log it and raise an exception, because you are unlikely to be able to continue properly.
2. Modify your exception code slightly to handle any other Exceptional cases:
```python
try:
    # requests.get() here
except Exception as err:
    print( "An exception occurred while contacting the FAA API" )
    # maybe include some details here about the URL you are trying to access
    # note that you probably don't even have a `response` object here to inspect the status code
    raise err # there is no use in continuing, so we just re-throw the exception
```
You could try to handle some specific exceptions from the `requests` module (detailed [here](https://requests.readthedocs.io/en/latest/api/#exceptions)) but I don't think it is really required in this case.

2023-10-03 22:16 UTC, tanminivan approved these changes

2023-10-04 06:04 UTC, chase-c55 approved these changes

2023-10-04 16:16 UTC, tanminivan commented
Don't forget to squash and rebase before the final merge!

2023-10-04 16:26 UTC, tanminivan approved these changes

2023-10-04 16:26 UTC, tanminivan commented on begin_end_notams.py
> +        return {}
I would would actually raise a new exception here, because this is a case that your program can't handle as part of a normal operation. We definitely want to "alert" on this use case and not continue. As is, if we hit this point, we would just have no notams in our dictionaries and we'd have to look at the logs to determine why.

Maybe something like:
```python
raise Exception("Received unexpected HTTP {response.status_code} from FAA API, unable to continue")
```

2023-10-04 19:23 UTC, tanminivan commented
nice

2023-10-09 05:06 UTC, tanminivan commented
I think this is ready for merge, right @Koy-Wilson ?

2023-10-09 20:12 UTC, merged