[NP-40] Get En route NOTAMs
CS4273-TeamViper/cs4273_fa2023_notams pull request #8
Opened 2023-10-09 20:36 UTC by Koy-Wilson

2023-10-09 21:15 UTC, tanminivan commented
Um, this looks like code you've already committed. How did you create this branch?

2023-10-09 21:59 UTC, Koy-Wilson commented
> Um, this looks like code you've already committed. How did you create this branch?

2023-10-11 01:28 UTC, chase-c55 requested changes

2023-10-11 01:28 UTC, chase-c55 commented on all_notams.py
> +    radians = 6371000
```suggestion
    METERS_TO_MILE = 1609
    RADIANS = 6371000
```

2023-10-11 01:28 UTC, chase-c55 commented on all_notams.py
> +main()
Delete this so it doesn't always call main. We will want to import this as a module to another python script probably and we don't want main running every time this script is imported.

2023-10-11 01:28 UTC, chase-c55 commented on all_notams.py
> +def main():
```suggestion
if __name__ == "__main__":
```

You can look this up, but this is how python does main functions. If you do this and delete the call to `main()` at the end of the file, this main function will still run when writing `python all_notams.py`, but when it is imported as a module to another script, main will not run. The reason I was getting double calls to the API was because your main function was written like this and was being called everytime this script was imported into my program.

2023-10-11 18:15 UTC, chase-c55 requested changes

2023-10-11 18:15 UTC, chase-c55 commented on all_notams.py
> +if __name__ == "main":
Sorry, but the underscores are important next to main. Example is `if __name__ == "__main__":`

See this for reference: [Explanation](https://stackoverflow.com/questions/419163/what-does-if-name-main-do)

2023-10-11 19:32 UTC, tanminivan requested changes

2023-10-11 19:32 UTC, tanminivan commented on all_notams.py
> +    lat_step = lat_step if (coord1[0] < coord2[0] and coord1[0] < 0) or (coord1[0] > coord2[0] and coord1[0] < 0) else -lat_step
Are lines 53 and 54 really required here? And is `abs()` required?

Thinking through this and showing my work. When we move from west to east, we want to add a positive step increment. When we move from east to west, we want to add a negative step increment.

I'm subtracting the destination longitude from the origin longitude. If I'm on a number line and I start at 3 and want to get to 10, I do `dest - orig` to find that I travelled 7 units. I think that this is backwards in your code, you are subtracting the destination from the origin (`orig - dest`).

I'm only working with longitude but I believe the same logic will apply to latitude.

```
# moving east to west in the western hemisphere, so we'll want to add a negative step increment
origin_long = -1
dest_long = -10

abs( dest_long ) - abs( origin_long ) = 1 - 10 = -9  # negative step, good. sign correction (lines 53-54) not required.
dest_long - origin_long = -10 - -1 = -9  # negative step, good. sign correction (lines 53-54) not required.

# moving east to west in the eastern hemisphere, so we'll want to add a negative step increment
origin_long = 13
dest_long = 7
abs( dest_long ) - abs( origin_long ) = 7 - 13 = -6  # negative step, good. sign correction (lines 53-54) not required.
dest_long - origin_long = 7 - 13 = -6  # negative step, good. sign correction (lines 53-54) not required.

# moving from west to east in the western hemisphere, we want a positive step increment
origin_long = -17
dest_long = -11
abs( dest_long ) - abs( origin_long ) =  11 - 17 = -6 # hmm, I don't think this is correct
dest_long - origin_long = -11 - -17 = 6  # positive step, good. sign correction (lines 53-54) not required.

# moving from west to east in the eastern hemisphere, we want a positive step increment
origin_long = 2
dest_long = 18
abs( dest_long ) - abs( origin_long ) = 18 - 2 = 16 # positive step, good. sign correction (lines 53-54) not required.
dest_long - origin_long = 18 - 2 = 16  # positive step, good. sign correction (lines 53-54) not required.

# moving across 0 from west to east, want a positive step increment
origin_long = -5
dest_long = 5
abs( dest_long ) - abs( origin_long ) = 5 - 5 = 0 # hmm, I don't think this is correct
dest_long - origin_long = 5 - -5 = 10  # this works though. positive step, good. sign correction (lines 53-54) not required.

# moving across 0 from east to west, want a negative step increment
origin_long = 5
dest_long = -5
abs( dest_long ) - abs( origin_long ) = 5 - 5 = 0 # hmm, I don't think this is correct
dest_long - origin_long = -5 - 5 = -10  # this works though. negative step, good. sign correction (lines 53-54) not required.
```

I think you can simply do `dest_long - origin_long` and you shouldn't have to manually handle the signs here, right?

Does that make sense? Maybe I made a mistake somewhere.

2023-10-11 19:32 UTC, tanminivan commented on all_notams.py
I am growing concerned about the organization of this project. This is feeling more and more like a collection of disparate python scripts and not like a unified, well-engineered software solution.

I see multiple copies of the `haversine()` function, here and in `haversine.py`.

There are multiple copies of `get_notams()`, in this file and in `begin_end_notams.py`. Some deal with locations and others with coordinates. They both duplicate making HTTP calls and handling pagination. What if there is a change required there and we change it in one place but not the other? This could be an opportunity for bugs. Which would should I code against?

How could this be refactored to eliminate code duplication?

2023-10-11 19:45 UTC, chase-c55 approved these changes

2023-10-11 20:33 UTC, Koy-Wilson commented on all_notams.py
> +    # Print out the starting and ending to ensure no infinite loop
There has not been an infinite loop. Furthermore, I don't see any world where it could happen. Since Haversine returns a double which we are casting to an int we should always have a finite number assuming that the airports input exist.

2023-10-11 20:43 UTC, Koy-Wilson commented on all_notams.py
> +    lat_step = lat_step if (coord1[0] < coord2[0] and coord1[0] < 0) or (coord1[0] > coord2[0] and coord1[0] < 0) else -lat_step
Maybe I'm overthinking it but since I am always going to be adding it together I thought it may have to be flipped. Using your first example of original as -1 and destination as -10. It would work without flipping for the first example when you do abs and add them together. However, it doesn't work with the example since we would add the step from -10 + -9 which would go to -19 - not -1. 

Using that logic it made more sense in my head to find the absolute value of it and then if the original lat/long < destination lat/long to negate the step.

2023-10-11 20:45 UTC, Koy-Wilson commented on all_notams.py
Haversine I deleted since it is the same function. We can delete begin_end_notams.py if you wish since it was just used for a proof of concept to show that we could store NOTAMs from the beginning and ending airport in a single dictionary but we will need the get_notams within all_notams.py since it properly handles coordinates.

2023-10-11 22:24 UTC, tanminivan commented on all_notams.py
> +    mile_step = miles_between_airports / 10
What about making this a parameter/constant so you can adjust more easily? Here and on line 28 where you specify the radius.

2023-10-11 22:24 UTC, tanminivan commented on all_notams.py
> +    # Print out the starting and ending to ensure no infinite loop
What if you put in the same coordinates for beginning and end?

2023-10-11 22:24 UTC, tanminivan commented on all_notams.py
> +    dictionary = {}
Would really like to avoid names like `dictionary`. What are we storing here?

2023-10-11 22:24 UTC, tanminivan commented on all_notams.py
> +        time.sleep(2)
might be worth a comment here about why we're sleeping here, to avoid overloading the API.

2023-10-11 22:24 UTC, tanminivan commented on all_notams.py
I would definitely look really closely and make sure you're deleting the right one (begin_end_notams vs this one).

Can you think of some ways to refactor this to reuse code?

2023-10-11 22:28 UTC, Koy-Wilson commented on all_notams.py
> +    # Print out the starting and ending to ensure no infinite loop
It loops over the miles_step in each iteration. Since the beginning and ending location are the same the distance is 0 which means the miles_step would be 0. Therefore, it would never enter the for loop

2023-10-12 14:01 UTC, LukeKirk0056 approved these changes

2023-10-13 00:57 UTC, Koy-Wilson commented on Airports.csv
We will have to redownload and upload the CSV for it to work if any are added.

2023-10-13 00:58 UTC, Koy-Wilson commented on all_notams.py
I'll go ahead and delete begin_end_notams and move the get_notams function to another file

2023-10-15 18:57 UTC, tanminivan commented on all_notams.py
> +    lat_step = lat_step if (coord1[0] < coord2[0] and coord1[0] < 0) or (coord1[0] > coord2[0] and coord1[0] < 0) else -lat_step
This definitely gets confusing quickly :)

I guess the first question is, how are coords to be represented? Are longitudes west of the prime meridian represented as negative values (-105) or just with a westerly designation (105°W)? I know we're just dealing with the continental US here, but ignore that for a moment.

> Maybe I'm overthinking it but since I am always going to be adding it together I thought it may have to be flipped.

I'm confused by your words here and the following examples you give. You say "adding" here but do you mean "subtracting"? Your code is subtracting the components of the coordinates, not adding them.

Regardless, I don't want this to hold up the PR, but it might be something to revisit later.

2023-10-15 19:36 UTC, tanminivan requested changes

2023-10-15 19:36 UTC, tanminivan commented on get_notams.py
> +    for index in range(1, total_pages + 1):
Duplicate code here, and line 50. Can this be refactored to eliminate duplication?

2023-10-15 19:36 UTC, tanminivan commented on get_notams.py
> +    print(f"Starting lat: {lat} and lon: {lon}")
So we're no longer getting NOTAMs for a specific departure and destination airport but rather by lat/long. Did we verify that we get the same NOTAMs? Are there any disadvantages to doing it this way?

2023-10-15 19:36 UTC, tanminivan commented on all_notams.py
> +    notamsArray = list(local_notams.values())
PEP8 would be `notams_array` or really `notams_list` or simply `notams`

2023-10-15 19:36 UTC, tanminivan commented on get_notams.py
> +        lat += lat_step
Not as part of this work, but I don't believe this is correct.

You are computing the haversine _distance_ but you aren't following the havesine _path_. I think this might be why you're off by a few miles.

Take a look here: https://www.movable-type.co.uk/scripts/latlong.html

Especially this image:
![image](https://github.com/CS4273-TeamViper/cs4273_fa2023_notams/assets/593822/7f2688cb-207d-43e9-b149-a5a2d37a4666)

This is plotting from 35°N,45°E to 35°N,135°E, from Baghdad to Osaka. The red line is the haversine distance (it takes into account the curvature of the earth), but I believe when you are calculating these intermediate points from the lat/long which will be the 35°N line of latitude (a direct easterly route that will be below the ride line).

I wouldn't fix this as part of this work but in a subsequent ticket.

2023-10-15 19:36 UTC, tanminivan commented on all_notams.py
You removed begin_end_notams but that code had all of your exception handling and I'm not sure what else. Are you sure that is what you want to remove?

2023-10-15 19:43 UTC, tanminivan commented
Just to clarify what I'm waiting on here:

- Refactoring get_notams to avoid code duplication
- Removal of begin_end_notams which had exception handling that is now gone
- Question about querying lat/long of the departure/destination airports instead of the airport codes themselves
- pep8 `notams_array`

We can discuss the other comments (about haversine path and lat/long math) Monday and I don't think it's required as part of this ticket, but something to track in another ticket.

2023-10-16 19:53 UTC, Koy-Wilson commented on get_notams.py
> +    print(f"Starting lat: {lat} and lon: {lon}")
We are still going to get them since we start at the beginning latitude and longitude and call it one more time on the end latitude and longitude. No disadvantages come to mind that I can think of besides possibly recalling the API an extra time at the end of the code.

2023-10-16 20:58 UTC, tanminivan approved these changes

2023-10-16 21:01 UTC, merged